_target_: src.criteria.HGTTRSetCriterion.HGTTRSetCriterion

matcher: ${matcher}

losses:
  loss_bbox:
    _target_: src.criteria.losses.BoxesLoss.BoxesLoss
    loss_l1_weight: 1
    loss_giou_weight: 2.5
    loss_weight: 2
  loss_label:
    _target_: src.criteria.losses.LabelLoss.LabelLoss
    loss_weight: 1
  loss_gaze_heatmap:
    _target_: src.criteria.losses.GazeHeatmapLoss.GazeHeatmapLoss
    loss_weight: 2
    gaze_heatmap_size: ${datamodule.gaze_heatmap_size}
